
INCLUDES        =    \
  hibit.h            \
  table_create.h     \
  table_create_int.h \
  table_ext.h        \
  table_int.h        \
  table_rcode.h      \
  table_read_int.h

ILIST   =        \
  table_create.h \
  table_rcode.h  \
  table_ext.h

EXPDIR  = /usr/include/

IDIR    = /usr/islarge/include/


.include <${RULES_MK}>
