IDIR    = /usr/islarge/lib/
ILIST   = libislarge.a

INCFLAGS += -I/usr/include

LIBRARIES       = libislarge.a
EXPLIB_TARGETS  = export_libislarge.a

OFILES  = table_read.o table_create.o

.include <${RULES_MK}>

